use_default_settings: true

general:
  instance_name: "searxng"

server:
  secret_key: "${SEARXNG_SECRET_KEY}"
  limiter: false
  public_instance: false
  method: "GET"

search:
  safe_search: 0
  default_lang: "en"
  autocomplete: ""
  formats:
    - json
  max_page: 5

outgoing:
  request_timeout: 15.0
  max_request_timeout: 30.0
  pool_connections: 100
  pool_maxsize: 20
  enable_http2: true
  retries: 2

engines:
  # General search engines
  - name: duckduckgo
    shortcut: ddg
    weight: 1.5
  - name: brave
    shortcut: br
    weight: 1.5
  - name: startpage
    shortcut: sp
    weight: 1.4
  - name: bing
    shortcut: bi
    weight: 1.3

  # Knowledge/Reference
  - name: wikipedia
    shortcut: wp
    weight: 1.5
  - name: wikidata
    shortcut: wd
    weight: 0.8
  - name: wikibooks
    shortcut: wb
    weight: 0.6
  - name: arch linux wiki
    shortcut: aw
    weight: 0.8
  - name: currency
    weight: 1.0

  # Developer resources
  - name: github
    shortcut: gh
    weight: 1.2
  - name: gitlab
    shortcut: gl
    weight: 0.8
  - name: stackoverflow
    shortcut: so
    weight: 1.2
  - name: mdn
    shortcut: mdn
    weight: 1.0
  - name: hackernews
    shortcut: hn
    weight: 0.8

  # Package registries
  - name: npm
    shortcut: npm
    weight: 0.8
  - name: pypi
    shortcut: pypi
    weight: 0.8
  - name: crates.io
    shortcut: crates
    weight: 0.8
  - name: pkg.go.dev
    shortcut: gopkg
    weight: 0.8
  - name: docker hub
    shortcut: dh
    weight: 0.8

  # Academic/Research
  - name: arxiv
    shortcut: arx
    weight: 1.5
  - name: semantic scholar
    shortcut: ss
    weight: 1.0
  - name: crossref
    shortcut: cr
    weight: 0.8
  - name: pubmed
    shortcut: pm
    weight: 0.8

  # Disabled engines
  - name: google
    disabled: true
  - name: yahoo
    disabled: true
  - name: yandex
    disabled: true
  - name: baidu
    disabled: true
  - name: qwant
    disabled: true
  - name: mojeek
    disabled: true
  - name: ahmia
    disabled: true
  - name: torch
    disabled: true
  - name: codeberg
    disabled: true
  - name: free software directory
    disabled: true
  - name: wikisource
    disabled: true
